import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const NavBar = () => {
  return (
    <nav className="bg-slate-950 py-4">
      <Link
        href="/"
        className="rounded-md border bg-orange-50 p-4 text-xl font-semibold"
      >
        Homepage
      </Link>
    </nav>
  );
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
